#!/usr/bin/env python3
"""Build the small embedded WASM TAR codec using Zig's bundled clang."""
import argparse,base64,hashlib,pathlib,subprocess
p=argparse.ArgumentParser();p.add_argument('--zig',default='zig');a=p.parse_args()
r=pathlib.Path(__file__).resolve().parent
subprocess.run([a.zig,'cc','-target','wasm32-freestanding','-O2','-nostdlib',
 '-Wl,-z,stack-size=65536','-Wl,--no-entry','-Wl,--export-memory','-Wl,--initial-memory=131072',
 *['-Wl,--export='+n for n in ['buffer_ptr','make_header','inspect_header','member_size']],
 str(r/'tar.c'),'-o',str(r/'tar.wasm')],check=True)
b=(r/'tar.wasm').read_bytes()
(r/'wasm.js').write_text('// Generated by build_wasm.py; source: tar.c (GPL-2.0-or-later).\n'
 'globalThis.RasterTarWasmBase64="'+base64.b64encode(b).decode()+'";\n')
print('tar.wasm SHA256:',hashlib.sha256(b).hexdigest())
